name: Test system rclip
description: Runs e2e tests on the rclip installed system-wide

inputs:
  python:
    description: 'Python version to use'
    required: false
    default: '3.10'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python }}
    - name: Print commit that we are going to run the tests from
      run: git rev-parse HEAD
      shell: bash
    - name: Install dev dependencies required to run e2e tests
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade poetry
        poetry install --no-root --only dev
      # here and below, passing `-ieo pipefail` to the shell to ensure it reads `.bashrc`
      shell: bash -ieo pipefail {0}
    - name: Print tested rclip version
      run: |
        which rclip
        rclip --version
      shell: bash -ieo pipefail {0}
    - run: make test-system-rclip
      shell: bash -ieo pipefail {0}
