name: Lint
description: Lint the codebase

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: '3.11'
    - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
    - name: Install Dependencies
      run: uv sync --locked
      shell: bash
    - run: make lint-style
      shell: bash
    - run: make lint-types
      shell: bash
