name: Lint
description: Lint the codebase

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Set up Node.js for pyright
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade poetry
        poetry install
      shell: bash
    - run: make lint-style
      shell: bash
    - run: make lint-types
      shell: bash
