name: Lint
description: Lint the codebase

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: '3.11'
    - uses: astral-sh/setup-uv@v8
    - name: Set up Node.js for pyright
      uses: actions/setup-node@v6
      with:
        node-version: '24.x'
    - name: Install Dependencies
      run: uv sync --locked
      shell: bash
    - run: make lint-style
      shell: bash
    - run: make lint-types
      shell: bash
