name: build

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Set up Node.js for pyright
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pipenv
          pipenv sync --dev
          pipenv run install_pyright
      - name: Check Style
        run: pipenv run check_style
      - name: Check Types
        run: pipenv run check_types

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pipenv
          pipenv sync --dev
      - name: Run Tests
        run: pipenv run test
