name: validate

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/lint

  test:
    strategy:
      matrix:
        python: ['3.11', '3.12', '3.13']
        # os: [ubuntu-22.04, macos-14, windows-2022]
        os: [macos-14, macos-15, macos-26]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Install Dependencies
        run: uv sync --locked
      - run: make test
        env:
          PYTHONFAULTHANDLER: '1'
